s3:
  defaults:
    host: s3.amazonaws.com
    port: 8080
    is_secure: yes
  main:
    user_id: AWS_USER_ID
    display_name: AWS_DISPLAY_NAME
    email: AWS_EMAIL
    access_key: AWS_ACCESS_KEY
    secret_key: AWS_SECRET_KEY
  alt:

    user_id: AWS_USER_ID
    display_name: AWS_DISPLAY_NAME
    email: AWS_EMAIL
    access_key: AWS_ACCESS_KEY
    secret_key: AWS_SECRET_KEY